# Generated by Django 3.0.7 on 2020-07-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0002_phdtable_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdtable',
            name='submission_year',
            field=models.CharField(max_length=100),
        ),
    ]
